---
- hosts: dbservers
  vars:
    crs_value: CRS="true"/>
    NEWGRIDHOME: /u01/app/19.22/grid
    OLDGRIDHOME: /u01/app/19.20/grid
    patch_dir: /u01/app/Setup
  remote_user: root
  tasks:

  - name: register cluster nodes for responsefile
    action:  shell echo $( {{ OLDGRIDHOME }}/bin/olsnodes | tr '\n' ',' | sed 's/,\s*$//')
    register: cluster_nodes

  - name: tag the new grid_home in inventory
    action: shell export NEWGRIDHOME={{ NEWGRIDHOME}}; $NEWGRIDHOME/gridSetup.sh -silent -switchGridHome oracle.install.option=CRS_SWONLY ORACLE_HOME={{ NEWGRIDHOME}} oracle.install.crs.config.clusterNodes={{ cluster_nodes.stdout }} oracle.install.crs.rootconfig.executeRootScript=false
    become: yes
    become_user: oracle
    
  - name: check crs flag in inventory
    action: shell grep {{ NEWGRIDHOME }} /u01/app/oraInventory/ContentsXML/inventory.xml | grep CRS | awk 'END { print $6 }'
    register: crsflag
    failed_when: crsflag.stdout !=  crs_value

  - name: execute root.sh and start grid from new home
    action: shell export NEWGRIDHOME={{ NEWGRIDHOME}}; $NEWGRIDHOME/root.sh
    throttle: 1

  - name: remove response file from stage directory
    file: path={{ patch_dir }}/grid_oop1922.rsp state=absent

  - name: Copy old grid home dependent files to the new grid home
    copy:
      src: "{{ OLDGRIDHOME }}/sqlplus/admin/glogin.sql"
      dest: "{{ NEWGRIDHOME }}/sqlplus/admin/"
      owner: oracle
      group: oinstall
      remote_src: yes

  - name: replace old_gridhome value in .bashrc files with the new_gridhome value
    action: shell sed -i 's@19.20/grid@19.22/grid@g' /root/.bashrc; sed -i 's@19.20/grid@19.22/grid@g' /home/oracle/.bashrc
    args:
      warn: false