---
- name: Prepare new grid home directories
  hosts: all
  remote_user: root

  vars:
    new_grid_home: /u01/app/19.22/grid
    patch_dir: /u01/app/Setup

  tasks:
    - name: Ensure patch directory exists
      ansible.builtin.file:
        path: "{{ patch_dir }}"
        state: directory
        owner: oracle
        group: oinstall

    - name: Ensure new grid home directory exists
      ansible.builtin.file:
        path: "{{ new_grid_home }}"
        state: directory
        owner: oracle
        group: oinstall