- name: Apply Oracle Database Release Update
  hosts: dbservers
  vars:
    u01_size_mb: 11045
    new_db_home: /u01/app/oracle/product/19.24/dbhome_1
    old_db_home: /u01/app/oracle/product/19.22/dbhome_1
    grid_home: /u01/app/19.24/grid
    patch_dir: /u01/app/Setup
    source_patch_dir: /u01/app/Setup
  remote_user: oracle
  run_once: true
  
  tasks:
    - name: Copy setup files to target server
      ansible.builtin.copy:
        src: "{{ source_patch_dir }}/"
        dest: "{{ patch_dir }}/"
        owner: oracle
        group: oinstall
        
    - name: Unzip new DB_HOME
      ansible.builtin.unarchive:
        src: "{{ patch_dir }}/LINUX.X64_193000_db_home.zip"
        dest: "{{ new_db_home }}"
        remote_src: yes

    - name: Unzip OPatch to new DB_HOME
      ansible.builtin.unarchive:
        src: "{{ patch_dir }}/p6880880_122010_Linux-x86-64.zip"
        dest: "{{ new_db_home }}"
        remote_src: yes

    - name: Prepare patches directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: oracle
        group: oinstall
      loop:
        - "{{ patch_dir }}/OJVM"

    - name: Unzip OJVM patch
      ansible.builtin.unarchive:
        src: "{{ patch_dir }}/p36414915_190000_Linux-x86-64.zip"
        dest: "{{ patch_dir }}/OJVM"
        remote_src: yes

    - name: unzip Data Pump Bundle patch
      ansible.builtin.unarchive:
        src: "{{ patch_dir }}/p36682332_1924000DBRU_Generic.zip"
        dest: "{{ patch_dir }}/GIRUOneOff"
        remote_src: yes

    - name: unzip Spatial Bundle patch
      ansible.builtin.unarchive:
        src: "{{ patch_dir }}/p37185000_1924000DBRU_Linux-x86-64.zip"
        dest: "{{ patch_dir }}/GIRUOneOff"
        remote_src: yes
        
    - name: unzip Spatial oneoff patch
      ansible.builtin.unarchive:
        src: "{{ patch_dir }}/p36875804_1924000DBRU_Linux-x86-64.zip"
        dest: "{{ patch_dir }}/GIRUOneOff"
        remote_src: yes
        
    - name: Register cluster nodes for response file
      ansible.builtin.shell: 
        cmd: "{{ grid_home }}/bin/olsnodes | tr '\n' ',' | sed 's/,$//'"
      register: cluster_nodes

    - name: Register osdba value for response file
      ansible.builtin.shell:
        cmd: "grep 'OSDBA_GROUP=' {{ old_db_home }}/install/response/db_20*.rsp"
      register: osdba

    - name: Register osoper value for response file
      ansible.builtin.shell:
        cmd: "grep 'OSOPER_GROUP=' {{ old_db_home }}/install/response/db_20*.rsp"
      register: osoper

    - name: Register osbackupdba value for response file
      ansible.builtin.shell:
        cmd: "grep 'OSBACKUPDBA_GROUP=' {{ old_db_home }}/install/response/db_20*.rsp"
      register: osbackupdba

    - name: Register osdgdba value for response file
      ansible.builtin.shell:
        cmd: "grep 'OSDGDBA_GROUP=' {{ old_db_home }}/install/response/db_20*.rsp"
      register: osdgdba

    - name: Register oskmdba value for response file
      ansible.builtin.shell:
        cmd: "grep 'OSKMDBA_GROUP=' {{ old_db_home }}/install/response/db_20*.rsp"
      register: oskmdba

    - name: Register osracdba value for response file
      ansible.builtin.shell:
        cmd: "grep 'OSRACDBA_GROUP=' {{ old_db_home }}/install/response/db_20*.rsp"
      register: osracdba

    - name: Create contents of response file
      ansible.builtin.copy:
        dest: "{{ patch_dir }}/db_oop.rsp"
        content: |
          oracle.install.responseFileVersion=/oracle/install/rspfmt_dbinstall_response_schema_v19.0.0
          oracle.install.option=INSTALL_DB_SWONLY
          UNIX_GROUP_NAME=oinstall
          INVENTORY_LOCATION=/u01/app/oraInventory
          ORACLE_BASE=/u01/app/oracle
          ORACLE_HOME={{ new_db_home }}
          oracle.install.db.InstallEdition=EE
          {{ osdba.stdout }}
          {{ osoper.stdout }}
          {{ osbackupdba.stdout }}
          {{ osdgdba.stdout }}
          {{ oskmdba.stdout }}
          {{ osracdba.stdout }}
          oracle.install.db.CLUSTER_NODES={{ cluster_nodes.stdout }}
          SECURITY_UPDATES_VIA_MYORACLESUPPORT=false
          DECLINE_SECURITY_UPDATES=true

    - name: Clean up DB home zip files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ patch_dir }}/LINUX.X64_193000_db_home.zip"
        - "{{ patch_dir }}/p36414915_190000_Linux-x86-64.zip"
        - "{{ patch_dir }}/p37106599_1924000DBRU_Linux-x86-64.zip"
        - "{{ patch_dir }}/p36582629_190000_Linux-x86-64.zip"
        - "{{ patch_dir }}/p34672698_1924000DBRU_Linux-x86-64.zip"
        - "{{ patch_dir }}/p36682332_1924000DBRU_Generic.zip"
        - "{{ patch_dir }}/p37185000_1924000DBRU_Linux-x86-64.zip"
        - "{{ patch_dir }}/p36875804_1924000DBRU_Linux-x86-64.zip"

    - name: Check u01 free disk space
      ansible.builtin.shell:
        cmd: "df -P /u01 | awk 'END { print $4 }'"
      register: u01size
      failed_when: u01size.stdout|int < u01_size_mb * 1024

    - name: Apply DBRU and one-offs
      ansible.builtin.shell:
        cmd: |
          {{ new_db_home }}/runInstaller -silent -ignorePrereqFailure -waitforcompletion \
          -applyRU {{ patch_dir }}/GIRU/36582629 \
          -applyOneOffs \
          {{ patch_dir }}/OJVM/36414915,{{ patch_dir }}/GIMRP/37106599/35016258,{{ patch_dir }}/GIMRP/37106599/35398148,{{ patch_dir }}/GIMRP/37106599/36126983,{{ patch_dir }}/GIMRP/37106599/36544236,{{ patch_dir }}/GIMRP/37106599/36611700,{{ patch_dir }}/GIMRP/37106599/36745665,{{ patch_dir }}/GIMRP/37106599/36916250,{{ patch_dir }}/GIMRP/37106599/36927520,{{ patch_dir }}/GIMRP/37106599/36943142,{{ patch_dir }}/GIMRP/37106599/36961299,{{ patch_dir }}/GIMRP/37106599/36988585,{{ patch_dir }}/GIMRP/37106599/37010561,{{ patch_dir }}/GIMRP/37106599/37048709,{{ patch_dir }}/GIMRP/37106599/37081891,{{ patch_dir }}/GIRUOneOff/34672698,{{ patch_dir }}/GIRUOneOff/36682332,{{ patch_dir }}/GIRUOneOff/37185000,{{ patch_dir }}/GIRUOneOff/36875804 \
          -responsefile {{ patch_dir }}/db_oop.rsp
      environment:
        CV_ASSUME_DISTID: OL7
        NEWDBHOME: "{{ new_db_home }}"
      register: apply_dbru
      failed_when: "'Successfully Setup Software' not in apply_dbru.stdout"
      async: 3600
      poll: 20

    - name: Output patching success message
      ansible.builtin.debug:
        msg: "Patching succeeded. InsaneDBA was here."
      when: apply_dbru.rc in [6,0]     
